---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
    ports:
      - 22181:22181
    logging:
      driver: none # change this to json-file if you want to debug kafka

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:19093
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    ports:
      - 19093:19093 # From outside docker network
    logging:
      driver: none # change this to json-file if you want to debug kafka

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:29093
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    ports:
      - 29092:29092
      - 29093:29093 # From outside docker network
    logging:
      driver: none # change this to json-file if you want to debug kafka

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092,PLAINTEXT_HOST://localhost:39093
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    ports:
      - 39092:39092
      - 39093:39093 # From outside docker network
    logging:
      driver: none # change this to json-file if you want to debug kafka

  kafka_setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    logging:
      driver: none # change this to json-file if you want to debug kafka setup

  golang_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - kafka_setup
    environment:
      KAFKA_TEST_BROKERS: kafka-1:19092,kafka-2:29092,kafka-3:39092