FROM confluentinc/cp-kafka

# Create the Kafka Topic & sleep forever
CMD bash -c "kafka-topics --delete --bootstrap-server kafka-1:19092 --topic integrationtest || true && sleep 1 && kafka-topics --create --bootstrap-server kafka-1:19092 --replication-factor 1 --partitions 3 --topic integrationtest && sleep infinity"