name: PR Conventions
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  label-pr:
    name: Auto-label PR
    runs-on: ubuntu-latest
    steps:
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'fix')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: "type: bug"
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'chore')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: "type: chore"
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'feat')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: "type: feature"

  lint:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
