name: PR Conventions
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
