on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          package-name: netlify-commons
          bump-minor-pre-major: true
          token: ${{ secrets.PKG_RELEASE_TOKEN }}
