on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@a9cd374e271b8aef573b8c16ac46c44fb89b02db
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}

      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          package-name: netlify-commons
          bump-minor-pre-major: true
          token: ${{ steps.get-token.outputs.token }}
